In [77]:
import pandas as pd
import ast
from ast import literal_eval

In [143]:
df = pd.read_csv('./airbnb-property-listings/tabular_data/listing.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 988 entries, 0 to 987
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    988 non-null    object
 1   Category              988 non-null    object
 2   Title                 988 non-null    object
 3   Description           900 non-null    object
 4   Amenities             988 non-null    object
 5   Location              988 non-null    object
 6   guests                969 non-null    object
 7   beds                  945 non-null    float64
 8   bathrooms             888 non-null    float64
 9   Price_Night           988 non-null    int64
 10  Cleanliness_rating    890 non-null    float64
 11  Accuracy_rating       890 non-null    float64
 12  Communication_rating  890 non-null    float64
 13  Location_rating       890 non-null    float64
 14  Check-in_rating       890 non-null    float64
 15  Value_rating          890 non-null    float64
 16  amenities_count       988 non-null    float64
 17  url                   988 non-null    object
 18  bedrooms              906 non-null    object
 19  Unnamed: 19           1 non-null      float64
dtypes: float64(10), int64(1), object(9)
memory usage: 154.5+ KB

In [144]:
df = df.dropna(subset = ["Cleanliness_rating", "Accuracy_rating", "Communication_rating", "Location_rating", "Check-in_rating", "Value_rating"])
df

,ID,Category,Title,Description,Amenities,Location,guests,beds,bathrooms,Price_Night,Cleanliness_rating,Accuracy_rating,Communication_rating,Location_rating,Check-in_rating,Value_rating,amenities_count,url,bedrooms,Unnamed: 19
0,f9dcbd09-32ac-41d9-a0b1-fdb2793378cf,Treehouses,Red Kite Tree Tent - Ynys Affalon,"['About this space', ""Escape to one of these t...","['What this place offers', 'Bathroom', 'Shampo...",Llandrindod Wells United Kingdom,2,1.0,1.0,105,4.6,4.7,4.3,5.0,4.3,4.3,13.0,https://www.airbnb.co.uk/rooms/26620994?adults...,NaN,NaN
1,1b4736a7-e73e-45bc-a9b5-d3e7fcf652fd,Treehouses,Az Alom Cabin - Treehouse Tree to Nature Cabin,"['About this space', ""Come and spend a romanti...","['What this place offers', 'Bedroom and laundr...",Guyonvelle Grand Est France,3,3.0,0.0,92,4.3,4.7,4.6,4.9,4.7,4.5,8.0,https://www.airbnb.co.uk/rooms/27055498?adults...,1,NaN
2,d577bc30-2222-4bef-a35e-a9825642aec4,Treehouses,Cabane Entre Les Pins\nüå≤üèïÔ∏èüå≤,"['About this space', 'Rustic cabin between the...","['What this place offers', 'Scenic views', 'Ga...",Duclair Normandie France,4,2.0,1.5,52,4.2,4.6,4.8,4.8,4.8,4.7,51.0,https://www.airbnb.co.uk/rooms/51427108?adults...,1,NaN
3,ca9cbfd4-7798-4e8d-8c17-d5a64fba0abc,Treehouses,Tree Top Cabin with log burner & private hot tub,"['About this space', 'The Tree top cabin is si...","['What this place offers', 'Bathroom', 'Hot wa...",Barmouth Wales United Kingdom,2,NaN,1.0,132,4.8,4.9,4.9,4.9,5.0,4.6,23.0,https://www.airbnb.co.uk/rooms/49543851?adults...,NaN,NaN
5,cfe479b9-c8f8-44af-9bc6-46ede9f14bb5,Treehouses,Treehouse near Paris Disney,"['About this space', 'Charming cabin nestled i...","['What this place offers', 'Bathroom', 'Hair d...",Le Plessis-Feu-Aussoux √éle-de-France France,4,3.0,1.0,143,5.0,4.9,5.0,4.7,5.0,4.7,32.0,https://www.airbnb.co.uk/rooms/935398?adults=1...,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,cfbc88da-e88c-415a-b397-108d0948c4ba,Beachfront,Lancing Beach Apartment,"['About this space', 'An apartment directly on...","['What this place offers', 'Bathroom', 'Hair d...",Lancing United Kingdom,4,2.0,1.5,240,4.9,5.0,5.0,5.0,4.9,4.8,33.0,https://www.airbnb.co.uk/rooms/12680472?adults...,2,NaN
983,4fea5054-f999-4c07-addc-67e4d893deab,Beachfront,Apartment,"['About this space', 'Light roomy space with o...","['What this place offers', 'Bathroom', 'Hair d...",Brighton and Hove England United Kingdom,2,1.0,1.0,78,4.8,5.0,4.9,4.9,5.0,4.9,54.0,https://www.airbnb.co.uk/rooms/48565992?adults...,1,NaN
984,282118e2-049e-4d9f-b2f2-b47477881b07,Beachfront,Sea front flat with a stunning view!,"['About this space', 'This specious two bedroo...","['What this place offers', 'Scenic views', 'Be...",East Sussex England United Kingdom,4,2.0,1.5,113,4.8,5.0,5.0,5.0,5.0,4.8,38.0,https://www.airbnb.co.uk/rooms/49742544?adults...,2,NaN
985,9ebf9cec-624e-480e-8704-dffa7cb1fe51,Beachfront,MP713 - Camber Sands Holiday Park - Sleeps 6 +...,"['About this space', 'With all the modern amen...","['What this place offers', 'Bathroom', 'Hot wa...",Camber England United Kingdom,6,3.0,2.0,80,4.7,4.8,5.0,5.0,5.0,4.7,24.0,https://www.airbnb.co.uk/rooms/47777462?adults...,2,NaN
987,d2b06c80-c643-485d-a24b-15d0811a3166,Beachfront,"Sea Scene's , Hayling Island","['About this space', 'Sea Scenes is a homely t...","['What this place offers', 'Bathroom', 'Hair d...",Hayling Island Hampshire United Kingdom,4,2.0,1.0,104,4.9,4.9,4.9,4.9,4.9,4.3,29.0,https://www.airbnb.co.uk/rooms/32377446?adults...,2,NaN

In [145]:
df.dropna(subset = ['Description'])
df['Description'] = df['Description'].astype(str)
df['Description'] = df['Description'].str.replace('About this space', '')
df['Description'] = df['Description'].str.replace('"', '')
df['Description'] = df['Description'].str.split(",")
df['Description'] = df['Description'].apply(lambda x: [i for i in x if i != ''])
df['Description'] = df['Description'].apply(lambda x: ''.join(x))
print(df['Description'][2])

['' 'Rustic cabin between the pines 3 meters high and 28 square meters on the banks of the Austreberth River üå≤üèïÔ∏èüå≤' 'The space' The space\nOur cabin between the pines is a great alternative for those looking for contact with nature and want to rest enjoy together or have fun with family or friends. With 3 meters high and 28 square meters it accommodates 4 people. Located on a 1.2 hectare property by the river Austreberthe our rustic treehouse shares the space with our garden rabbits and dumplings as well as wild dumplings and our beloved khenty mare who loves apples and carrots. A tranquil retreat with efficient thermal insulation and heaters for the colder days. Equipped with a double bed sofa bed kitchen  duvet and toilet.\n\n\nWe provide:\nTowels\nBed linens and pillows\nKitchen detergent and bathroom soap\nPaper towels & toilet paper\nCooking utensils\nCoffee tea salt and pepper herbs of provence\nWhat to do in the area's guide\n\nI'll follow us on Instagram @entreespins 'Guest access' 'Guest access\nGuests can use the space around the cabin.' 'Other things to note' Other things to note\n*When it's windy the cabin squeaks but there's nothing to worry about.\n\n*Do not use candles or objects containing a fire inside and outside the cabin as the polyester is flammable.\n\n*Smoking outside only please.\n\n*Our dear pets are allowed but with the commitment of their guardian not to leave them on the bed and furnishing fabrics as well as being responsible for their waste.\n\n*Pine needles often fall on the balcony which doesn't mean the space hasn't been cleaned.\n\n*As this is literally a house between the trees it is common that there are insects and cobwebs outside but with the door closed it will prevent them from entering the cabin.\n\n*With the arrival of the cold season we see that the internal temperature is between 15 and 18 degrees.\n\n*Check-out time must be respected so as not to change the arrival time of the next guest.]

In [73]:
df['Description'] = df['Description'].apply(lambda x: ast.literal_eval(x))

# Remove empty quotes and "About this space" prefix from the lists
df['Description'] = df['Description'].apply(lambda x: [i.replace('"', '').replace('About this space', '') for i in x if i != ''])

# Join the list items with a whitespace
df['Description'] = df['Description'].apply(lambda x: ' '.join(x))

# Remove records with a missing description
df = df[df['Description'].notnull()]

ValueError: malformed node or string: nan

In [127]:
df['Description'] = df['Description'].str.replace('About this space', '')
df['Description'] = df['Description'].apply(lambda x: [item for item in eval(str(x)) if item != ''])
df['Description'] = df['Description'].apply(lambda x: ''.join(x))

NameError: name 'nan' is not defined